apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    name: postgres-db
    app: sample-voting-app
spec:
  containers:
  - name: postgres-db-container
    image: postgres
    ports:
    - containerPort: 5432
  env:
  - name: POSTGRES_USER
    value: "postgres"
  - name: POSTGRES_PASSWORD
    value: "postgres"
  - name: POSTGRES_HOST_AUTH_METHOD
    value: trust
