apiVersion: v1
kind: Pod
metadata:
  name: redis_db
  labels:
    name: redis_db
    app: sample-voting-app
spec:
  containers:
    - name: redis_db_container
      image: redis
      ports:
        - containerPort: 6379