apiVersion: v1
kind: Pod
metadata:
  name: result-page
  labels:
    name: result-page
    app: sample-voting-app
spec:
  containers:
    - name: frontend-voting
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80