apiVersion: v1
kind: Pod
metadata:
  name: voting-page
  labels:
    name: voting-page
    app: sample-voting-app
  spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80