apiVersion: v1 
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  selector:
    name: result-page
    app: sample-voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30015