apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  type: NodePort
  selector:
    name: voting-page
    app: sample-voting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
 
  