apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres_deployment
  labels:
    app: sample-voting-app
spec:
  selector:
    matchLabels:
      name: postgres_db
      app: sample-voting-app
  template:
    metadata:
      name: postgres_db
      labels:
        name: postgres_db
        app: sample-voting-app
    spec:
      containers:
        - name: postgres_db_container
          image: postgres:16.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust