apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    app: sample-voting-app
spec:
  selector:
    matchLabels:
      name: worker-pod
      app: sample-voting-app
  template:
     metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: sample-voting-app
     spec:
        containers:
          - name: worker-app
            image: kodekloud/examplevotingapp_worker:v1
     